title: Kunal Manjare
#logo: 
description: Computer Science Master's student at the University of Utah. Very desirous about innovation, new projects and automation. Always seeking for knowledge and practical implementation, love for cars, Technology as well as love for coding and engineering.
show_downloads: true
theme: jekyll-theme-minimal
